### ISSUE TITLE
different estimates of crossed and mixed-membership random effects

### ISSUE THREAD

**Issue by drjhw** [CDCgov/cfa-gam-rt#46]
I have an unbalanced design which derives the same biochemical measure for people in different assays. So, assay and person are (partially) crossed, or the biochemical data have mixed membership in both people and assay factors.

I puzzled over the distinction between crossed and mix-membership random effects. I am a clinician, not a statistician. So, for me the simplest way to answer the question is to analyse the data both ways and compare the resulting random effects. I did that.

The random effects from the two approaches correlate very strongly (r=0.999). However, the Estimates of the random effects from the mixed-membership design are (almost) exactly *double* those from the crossed design.

The fixed effects coefficients from the two designs are very similar.

The two-fold discrepancy between the scales of the estimates of the fixed and random effects in the designs with crossed and mixed-membership random effects is puzzling. Is it a bug?

I am using brms version 2.21.0 on Rstudio 2023.12.0 Build 369, running R version 4.4.0 on Linux Ubuntu (v 22.04)

**Comment by zsusswein** [comment]
Hey @drjhw! Thanks for opening an issue. This repo is focused on developing an R package `RtGam`. It sounds like your issue is focused on implementing a model in `brms`.

I'd encourage you to ask your question on the [Stan forums](https://discourse.mc-stan.org). I'm going to close the issue here because I don't see a connection to the `RtGam` package.
